spring:
    datasource:
        url: jdbc:h2:mem:inventory
        driverClassName: org.h2.Driver
        username: sa
        hikari:
            maximumPoolSize: 10
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
logging:
    file:
        path: ./target
    level:
        root: INFO
        "[com.e3.api.inventory_service]": INFO
        "[org.springframework.web]": INFO
        "[org.springframework.security]": INFO
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        metrics:
            enabled: true
