spring:
    application:
        name: inventory-service
    datasource:
        url: jdbc:postgresql://localhost:5432/inventory
        username: postgres
        password: postgres
        hikari:
            connectionTimeout: 30000
            maximumPoolSize: 10
            maxLifetime: 30000
            idleTimeout: 30000
            validationTimeout: 30000
            initializationFailTimeout: 30000
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    batch_size: 50
                order_inserts: true
                order_updates: true
logging:
    level:
        root: INFO
        com:
            e3: DEBUG